"use client";

import { Coffee, LayoutDashboard, PackageOpen, ShoppingBasket, Store, Users } from "lucide-react";
import Link from "next/link";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

export type DashboardProduct = { productId: string; name: string; categoryId: string; salePrice: number; unitCost: number; monthlyRevenue: number; monthlyCost: number; costRate: number | null; quantitySold: number };
export type DashboardData = { targetMonth: string; totalRevenue: number; totalCost: number; costRate: number | null; quantitySold: number; products: DashboardProduct[] };
export type DashboardMonthPoint = { month: string; cost: number | null };
type CategorySale = { name: string; revenue: number; value: number };

const yen = (value: number) => `${new Intl.NumberFormat("ja-JP", { maximumFractionDigits: 0 }).format(value)}円`;
const percent = (value: number | null) => value == null ? "-" : `${(value * 100).toFixed(1)}%`;
function percentageChange(current: number, previous: number | undefined) { return previous && previous !== 0 ? `${current >= previous ? "+" : ""}${((current - previous) / previous * 100).toFixed(1)}%` : "比較なし"; }

export function DashboardView({ data, previous, history, categorySales, targetMonth, isAdmin, displayName, hasError }: { data: DashboardData; previous: DashboardData | null; history: DashboardMonthPoint[]; categorySales: CategorySale[]; targetMonth: string; isAdmin: boolean; displayName: string; hasError: boolean }) {
  const navItems = isAdmin ? [[LayoutDashboard, "ダッシュボード", "/"], [PackageOpen, "商品マスタ", "/admin/products"], [ShoppingBasket, "材料マスタ", "/admin/ingredients"], [Store, "購入先・仕入価格", "/admin/suppliers"], [Users, "販売実績", "/admin/sales"]] as const : [[LayoutDashboard, "ダッシュボード", "/"], [PackageOpen, "商品一覧", "/products"]] as const;
  const [year, month] = targetMonth.split("-");
  const cards = [
    ["月間売上", yen(Number(data.totalRevenue)), percentageChange(Number(data.totalRevenue), previous ? Number(previous.totalRevenue) : undefined)],
    ["トータル原価", yen(Number(data.totalCost)), percentageChange(Number(data.totalCost), previous ? Number(previous.totalCost) : undefined)],
    ["平均原価率", percent(data.costRate == null ? null : Number(data.costRate)), data.costRate != null && previous?.costRate != null ? `${(Number(data.costRate) * 100 - Number(previous.costRate) * 100).toFixed(1)}pt` : "比較なし"],
    ["販売個数", `${Number(data.quantitySold).toLocaleString("ja-JP")}個`, previous ? `${Number(data.quantitySold) - Number(previous.quantitySold) >= 0 ? "+" : ""}${Number(data.quantitySold) - Number(previous.quantitySold)}個` : "比較なし"],
  ] as const;

  return <div className="min-h-screen bg-[#f6f3ee] text-[#28251f]">
    <aside className="fixed inset-y-0 left-0 hidden w-64 flex-col bg-[#183c35] px-5 py-7 text-white lg:flex"><Brand /><nav className="mt-10 space-y-2">{navItems.map(([Icon, label, href], index) => <Link href={href} key={label} className={`flex w-full items-center gap-3 rounded-xl px-4 py-3 text-sm transition ${index === 0 ? "bg-white/14 font-semibold" : "text-emerald-50/70 hover:bg-white/8 hover:text-white"}`}><Icon size={18} />{label}</Link>)}</nav><div className="mt-auto rounded-2xl bg-white/8 p-4"><p className="text-xs text-emerald-100/60">ログイン中</p><p className="mt-1 text-sm font-semibold">{displayName}</p><p className="mt-1 text-xs text-emerald-100/60">{isAdmin ? "管理者" : "一般ユーザー"}</p></div></aside>
    <main className="px-5 py-6 lg:ml-64 lg:px-9 lg:py-8"><div className="mb-5 flex gap-2 overflow-x-auto pb-1 lg:hidden">{navItems.map(([, label, href]) => <Link href={href} key={label} className="whitespace-nowrap rounded-xl border border-stone-200 bg-white px-3 py-2 text-xs font-semibold">{label}</Link>)}</div>
      <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-[#b66d27]">{year}年{Number(month)}月</p><h1 className="mt-1 text-3xl font-bold tracking-tight">原価ダッシュボード</h1><p className="mt-2 text-sm text-stone-500">販売実績を基準に、月間の原価状況を確認できます。</p></div><form className="flex items-end gap-2" method="get"><label className="grid gap-1 text-xs text-stone-500">対象月<input className="master-input" name="month" type="month" defaultValue={targetMonth} /></label><button className="rounded-xl border border-stone-200 bg-white px-4 py-2.5 text-sm font-semibold shadow-sm" type="submit">表示</button></form></header>
      {hasError && <div role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">ダッシュボードデータの一部を取得できませんでした。</div>}
      <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, change]) => <article key={label} className="rounded-2xl border border-stone-200/80 bg-white p-5 shadow-[0_8px_24px_rgba(60,50,35,0.04)]"><p className="text-sm text-stone-500">{label}</p><p className="mt-3 text-2xl font-bold tracking-tight">{value}</p><p className="mt-3 text-xs font-semibold text-stone-500">{change} <span className="font-normal text-stone-400">前月比</span></p></article>)}</section>
      {data.products.length === 0 && <div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-800">この月は原価計算データがありません。{isAdmin ? "販売実績画面で販売個数を保存し、原価を再計算してください。" : "管理者による月次原価計算後に表示されます。"}</div>}
      <section className="mt-5 grid gap-5 xl:grid-cols-[1.35fr_1fr]"><ChartCard title="月別原価率" subtitle="過去6か月の推移"><LineChart data={history}><CartesianGrid stroke="#eee9df" strokeDasharray="4 4" vertical={false} /><XAxis dataKey="month" axisLine={false} tickLine={false} /><YAxis domain={[0, 100]} axisLine={false} tickLine={false} unit="%" /><Tooltip formatter={(value) => [value == null ? "-" : `${Number(value).toFixed(1)}%`, "原価率"]} /><Line type="monotone" dataKey="cost" connectNulls={false} stroke="#cc7b2b" strokeWidth={3} dot={{ r: 4, fill: "#fff", strokeWidth: 3 }} /></LineChart></ChartCard><ChartCard title="カテゴリ別売上" subtitle="税込販売価格 × 販売個数"><BarChart data={categorySales}><CartesianGrid stroke="#eee9df" strokeDasharray="4 4" vertical={false} /><XAxis dataKey="name" axisLine={false} tickLine={false} /><YAxis domain={[0, 100]} axisLine={false} tickLine={false} unit="%" /><Tooltip formatter={(value) => [`${Number(value).toFixed(1)}%`, "売上構成"]} /><Bar dataKey="value" fill="#316c5e" radius={[8, 8, 2, 2]} /></BarChart></ChartCard></section>
      <section className="mt-5 rounded-2xl border border-stone-200/80 bg-white p-6 shadow-[0_8px_24px_rgba(60,50,35,0.04)]"><div className="flex items-center justify-between"><div><h2 className="font-bold">商品別原価</h2><p className="mt-1 text-xs text-stone-400">計算済みスナップショット</p></div><Link className="text-sm font-semibold text-[#a45f20]" href="/products">商品一覧 →</Link></div>{data.products.length === 0 ? <p className="mt-5 text-sm text-stone-500">表示できる商品別原価はありません。</p> : <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b border-stone-100 text-xs text-stone-400"><tr><th className="pb-3">商品</th><th className="pb-3">1個原価</th><th className="pb-3">税込販売価格</th><th className="pb-3">販売個数</th><th className="pb-3">原価率</th></tr></thead><tbody>{data.products.map((item) => <tr key={item.productId} className="border-b border-stone-100 last:border-0"><td className="py-4 font-semibold"><Link href={`/products/${item.productId}`}>{item.name}</Link></td><td className="py-4">{yen(Number(item.unitCost))}</td><td className="py-4 text-stone-500">{yen(Number(item.salePrice))}</td><td className="py-4">{Number(item.quantitySold).toLocaleString("ja-JP")}個</td><td className="py-4">{percent(item.costRate == null ? null : Number(item.costRate))}</td></tr>)}</tbody></table></div>}</section>
    </main>
  </div>;
}

function Brand() { return <div className="flex items-center gap-3 px-2"><div className="grid size-10 place-items-center rounded-xl bg-[#f2ae41] text-[#183c35]"><Coffee size={22} strokeWidth={2.5} /></div><div><p className="text-lg font-bold tracking-wide">COST TABLE</p><p className="text-xs text-emerald-100/70">原価管理システム</p></div></div>; }
function ChartCard({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactElement }) { return <article className="rounded-2xl border border-stone-200/80 bg-white p-6 shadow-[0_8px_24px_rgba(60,50,35,0.04)]"><div><h2 className="font-bold">{title}</h2><p className="mt-1 text-xs text-stone-400">{subtitle}</p></div><div className="mt-6 h-64"><ResponsiveContainer width="100%" height="100%">{children}</ResponsiveContainer></div></article>; }
